# Generated by Django 5.1.2 on 2024-10-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
